language: node_js
services: mongodb
node_js:
  - "0.10.28"
before_install: npm install -g grunt-cli
install: npm install
before_script: 
  - grunt exec:killDB
  - grunt exec:startFirstDB
  - sleep 15
  - grunt exec:createMongoUsers
  - grunt exec:killDB
  - grunt exec:startDB
  - grunt initSystem -username test -password test -email test@test.com
  - grunt reinstall
script: grunt tests