language: node_js
services: mongodb
node_js:
  - "0.10.28"
before_install: npm install -g grunt-cli
install: npm install
before_script: 
  - grunt exec:startFirstDB
  - grunt exec:createMongoUsers -username test -password test -test test@test.com
  - grunt exec:killDB
  - grunt exec:startDB
  - grunt initSystem
  - grunt reinstall
script: grunt mocha